version: 2

build:
  os: ubuntu-20.04
  tools:
    nodejs: "19"
    python: "3.9"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install
      # DEBUG: test module installed with Poetry can be imported
      - python -c "import cadquery; print(cadquery.__version__)"
      # DEBUG: test current project `sphinxcontrib.cadquery` can be imported
      - python -c "import sphinxcontrib.cadquery; print(sphinxcontrib.cadquery.__version__)"
      - npm clean-install
      - make npm-build

sphinx:
  configuration: docs/conf.py
