version: 2

build:
  os: ubuntu-20.04
  tools:
    nodejs: "19"
    python: "3.11"
  jobs:
   pre_install:
     - npm clean-install
     - make npm-build
   post_install:
    - pip install poetry
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install

sphinx:
  configuration: docs/conf.py
